#!/usr/bin/env bash

cd "$(dirname "$0")"

MAIN_OBJ='./cinc'
ROOT="$(pwd)"
DOCK="docker run --rm -v ${ROOT}:/cinc -w /cinc compilerbook"

assert() {
  expected="$1"
  input="$2"

  $DOCK "$MAIN_OBJ" "$input" > tmp.s
  $DOCK cc tmp.s -o tmp
  $DOCK ./tmp
  actual="$?"

  if [ "$actual" = "$expected" ]; then
    echo "ok: $input => $actual"
  else
    echo "err: $input => $expected expected, but got $actual"
    exit 1
  fi
}

assert 0 0
assert 42 42

echo 'all tests passed'

